# Generated by Django 4.0.3 on 2022-03-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_productcategory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
