# Generated by Django 4.0.3 on 2022-03-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_number',
            field=models.IntegerField(),
        ),
    ]
