# Generated by Django 4.0.3 on 2022-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_student_std_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_number',
            field=models.CharField(max_length=10),
        ),
    ]
