# Generated by Django 4.0.3 on 2022-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_student_std_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
