# Generated by Django 4.0.3 on 2022-03-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
